### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by pstew** [pbnjay/lollipops#37] opened 2018-06-04 22:45 UTC
Hello, I'm trying the example provided in the readme. Can you please help with the following error with release v1.3.2 for Macs?

`$ ./lollipops TP53 R273C R175H T125 R248Q`
`HGNC Symbol:  TP53`
`Get http://www.uniprot.org/uniprot/?query=TP53+AND+reviewed:yes+AND+organism:9606+AND+database:pfam&sort=score&columns=id,entry+name,reviewed,genes,organism&format=tab: dial tcp 35.178.50.247:80: i/o timeout`

If it helps I can ping 35.178.50.247 just fine. 

Thank you!

**Comment by pbnjay** [comment] 2018-06-04 22:53
Duplicate of issues #28 #33 and #35. Try again later or from a different internet connection. Please use the search next time.

**Closed by pbnjay** 2018-06-04 22:53 UTC
