### ISSUE TITLE
Support for mapping AA to a gene level view instead of protein

### ISSUE THREAD

**Issue by dannydesloover2** [pbnjay/lollipops#29] opened 2017-11-27 23:38 UTC
As a potential segway to support visualizing CNVs, it would be nice to map against genomic coordinates.  Accepting c. nomenclature, for example.    Many of the domains in Uniprot are incorrect :)

**Comment by pbnjay** [comment] 2017-11-28 04:56
Duplicate of #4, #21, and #25. Happy to accept pull requests

**Closed by pbnjay** 2017-11-28 04:56 UTC
